import OpenAI from "openai";

import type { Application, Settings } from "./types";

export interface GeneratedEmail {
  subject: string;
  body: string;
  source: "ai" | "template";
}

const MAX_RESUME_CHARS = 8000;

/**
 * Creates the signature/contact block.
 * This is always appended by the application,
 * not generated by AI.
 */
function signatureBlock(s: Settings): string {
  const lines = [
    s.name
      ? `Best regards,\n${s.name}`
      : "Best regards",
  ];

  if (s.phone) {
    lines.push(`Phone: ${s.phone}`);
  }

  if (s.linkedin) {
    lines.push(`LinkedIn: ${s.linkedin}`);
  }

  if (s.portfolio) {
    lines.push(`Portfolio: ${s.portfolio}`);
  }

  return lines.join("\n");
}

/**
 * Creates a fixed and predictable email subject.
 *
 * Examples:
 * Application for React Developer at Hello Tech
 * Application for Full Stack Developer
 * Job Application
 */
function createSubject(
  app: Pick<Application, "company" | "position">
): string {
  const position = app.position?.trim();
  const company = app.company?.trim();

  // No position available
  if (!position) {
    return "Job Application";
  }

  // Position and company available
  if (company) {
    return `Application for ${position} at ${company}`
      .slice(0, 200);
  }

  // Only position available
  return `Application for ${position}`
    .slice(0, 200);
}

/**
 * Fallback email used when:
 * - AI is disabled
 * - API key is missing
 * - AI request fails
 * - AI returns invalid output
 */
export function templateEmail(
  app: Pick<Application, "company" | "position">,
  s: Settings
): GeneratedEmail {
  const company = app.company?.trim();
  const position =
    app.position?.trim() || "the position";

  const subject = createSubject(app);

  const introduction = company
    ? `I'm ${s.name || "a candidate"}, and I'm applying for the ${position} position at ${company}.`
    : `I'm ${s.name || "a candidate"}, and I'm applying for the ${position} position.`;

  const experience = s.experienceSummary
    ? `${s.experienceSummary} I believe my technical background and experience could allow me to contribute effectively to the role.`
    : "I have a technical background and experience that I believe could allow me to contribute effectively to the role.";

  const body = [
    "Dear Hiring Team,",
    "",
    introduction,
    "",
    experience,
    "",
    "I've attached my resume for your consideration and would appreciate the opportunity to discuss how my skills and experience align with this role.",
    "",
    "Thank you for your time and consideration.",
    "",
    signatureBlock(s),
  ].join("\n");

  return {
    subject,
    body,
    source: "template",
  };
}

/**
 * Extracts JSON from the AI response.
 *
 * Supports:
 *
 * {"body":"..."}
 *
 * and:
 *
 * ```json
 * {"body":"..."}
 * ```
 */
function extractJson(
  raw: string
): { body?: string } {
  if (!raw) {
    return {};
  }

  const fenced = raw.match(
    /```(?:json)?\s*([\s\S]*?)```/i
  );

  const candidate = fenced
    ? fenced[1]
    : raw;

  const start = candidate.indexOf("{");
  const end = candidate.lastIndexOf("}");

  if (
    start !== -1 &&
    end !== -1 &&
    end > start
  ) {
    try {
      const parsed = JSON.parse(
        candidate.slice(start, end + 1)
      );

      return {
        body:
          typeof parsed.body === "string"
            ? parsed.body
            : undefined,
      };
    } catch {
      // Invalid JSON
    }
  }

  return {};
}

/**
 * Removes any signature generated accidentally by AI.
 */
function removeGeneratedSignature(
  body: string
): string {
  const signaturePattern =
    /\n\s*(?:Best regards|Regards|Kind regards|Warm regards|Sincerely|Thanks)[,!.\s]*\n[\s\S]*$/i;

  return body
    .replace(signaturePattern, "")
    .trimEnd();
}

/**
 * Removes contact information generated by AI.
 *
 * The application will append the real contact block.
 */
function removeGeneratedContactInfo(
  body: string
): string {
  return body
    .replace(
      /\n?(?:Phone|Email|E-mail|LinkedIn|Portfolio|Website)\s*:\s*.*$/gim,
      ""
    )
    .trim();
}

/**
 * Cleans the AI-generated email.
 */
function cleanGeneratedBody(
  body: string
): string {
  let cleaned = body.trim();

  // Remove markdown formatting
  cleaned = cleaned
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1");

  // Remove generated contact details
  cleaned = removeGeneratedContactInfo(cleaned);

  // Remove generated signature
  cleaned = removeGeneratedSignature(cleaned);

  // Remove excessive blank lines
  cleaned = cleaned.replace(/\n{3,}/g, "\n\n");

  return cleaned.trim();
}

/**
 * Generates a personalized job application email.
 *
 * AI ONLY generates the email body.
 * The subject is always generated by createSubject().
 */
export async function generateEmail(
  app: Pick<Application, "company" | "position">,
  settings: Settings,
  resumeText: string,
  resumeFilename: string
): Promise<GeneratedEmail> {
  /**
   * Use template if AI is disabled or
   * no API key is available.
   */
  if (
    !settings.aiEnabled ||
    !settings.aiApiKey
  ) {
    return templateEmail(app, settings);
  }

  const client = new OpenAI({
    apiKey: settings.aiApiKey,

    baseURL:
      settings.aiBaseUrl || undefined,

    timeout: 60000,

    maxRetries: 1,
  });

  const position =
    app.position?.trim() ||
    "a suitable position";

  const company =
    app.company?.trim() || "";

  /**
   * Limit resume size to control token usage.
   */
  const resumeSnippet = resumeText
    ? `
CANDIDATE RESUME
File: ${resumeFilename || "resume"}

"""
${resumeText.slice(0, MAX_RESUME_CHARS)}
"""
`
    : "";

  /**
   * AI instructions.
   *
   * IMPORTANT:
   * AI generates ONLY the body.
   * The subject is controlled by JavaScript.
   */
  const systemPrompt = [
    "You are an expert job application email writer.",
    "",
    "Your task is to write a short, personalized, professional job application email for a real candidate.",
    "",
    "The email must sound natural and human. It should feel like the candidate personally wrote it, not like generic AI-generated content or a formal cover letter.",
    "",
    "CONTENT RULES:",
    "- Use information ONLY from the candidate profile and resume.",
    "- Never invent skills, technologies, work experience, achievements, education, companies, projects, or numbers.",
    "- Identify the candidate's skills and experience most relevant to the requested position.",
    "- Mention only 2 to 5 relevant technical skills or areas of experience.",
    "- Do not list every technology from the resume.",
    "- Explain the skills naturally instead of simply listing them.",
    "- You may mention relevant practical work or project experience if supported by the resume.",
    "- Do not exaggerate experience or abilities.",
    "- Do not blindly repeat the resume.",
    "- Do not invent information about the company.",
    "",
    "EMAIL STRUCTURE:",
    "- Plain text only.",
    "- No markdown.",
    "- No bullet points.",
    "- No numbered lists.",
    "- Start with a natural greeting such as 'Dear Hiring Team,' or 'Dear Hiring Manager,'.",
    "- Paragraph 1: Introduce the candidate and clearly mention that they are applying for the POSITION.",
    "- If a company is provided, naturally mention the COMPANY.",
    "- Paragraph 2: Highlight the strongest and most relevant skills or experience for the role.",
    "- Paragraph 3: Mention that the resume is attached and express interest in discussing the opportunity.",
    "- End with a sentence similar to 'Thank you for your time and consideration.'",
    "",
    "SIGNATURE RULE:",
    "- Do NOT write a sign-off.",
    "- Do NOT write 'Best regards', 'Regards', 'Sincerely', 'Thanks', or similar phrases.",
    "- Do NOT include the candidate's name.",
    "- Do NOT include phone number.",
    "- Do NOT include email.",
    "- Do NOT include LinkedIn.",
    "- Do NOT include portfolio or website.",
    "- The application automatically appends the real signature.",
    "",
    "STYLE:",
    "- Professional, warm, and confident.",
    "- Humble and natural.",
    "- Clear and conversational.",
    "- Avoid corporate buzzwords.",
    "- Avoid unnecessary filler.",
    "- Do not sound like a formal cover letter.",
    "- Do not sound overly enthusiastic or desperate.",
    "- Target approximately 120 to 170 words.",
    "",
    "AVOID THESE PHRASES:",
    "- 'I am writing to express my interest'",
    "- 'esteemed organization'",
    "- 'perfect fit'",
    "- 'proven track record'",
    "- 'results-driven'",
    "- 'passionate about'",
    "- 'leverage'",
    "- 'furthermore'",
    "- 'moreover'",
    "- 'dynamic organization'",
    "- 'synergy'",
    "- 'thrilled to apply'",
    "- 'I would be honored'",
    "",
    "OUTPUT RULES:",
    "- Generate ONLY the email body.",
    "- Do NOT generate a subject line.",
    "- Respond with STRICT valid JSON only.",
    '- Use exactly this structure: {"body":"..."}',
    "- Do not include markdown code fences.",
    "- Do not include explanations before or after the JSON.",
  ].join("\n");

  /**
   * Candidate and job information.
   */
  const userPrompt = [
    `POSITION: ${position}`,

    company
      ? `COMPANY: ${company}`
      : "COMPANY: Not provided",

    "",

    "CANDIDATE PROFILE:",

    `Name: ${
      settings.name || "(unknown)"
    }`,

    `Experience Summary: ${
      settings.experienceSummary ||
      "(use the resume to determine experience)"
    }`,

    "",

    resumeSnippet,
  ].join("\n");

  const messages = [
    {
      role: "system" as const,
      content: systemPrompt,
    },
    {
      role: "user" as const,
      content: userPrompt,
    },
  ];

  try {
    let raw = "";

    try {
      /**
       * Preferred request using JSON mode.
       */
      const completion =
        await client.chat.completions.create({
          model:
            settings.aiModel ||
            "gpt-4o-mini",

          temperature: 0.45,

          messages,

          response_format: {
            type: "json_object",
          },
        });

      raw =
        completion.choices[0]
          ?.message?.content ?? "";
    } catch {
      /**
       * Some OpenAI-compatible APIs do not
       * support response_format.
       *
       * Retry without JSON mode.
       */
      const completion =
        await client.chat.completions.create({
          model:
            settings.aiModel ||
            "gpt-4o-mini",

          temperature: 0.45,

          messages,
        });

      raw =
        completion.choices[0]
          ?.message?.content ?? "";
    }

    /**
     * Parse the AI response.
     */
    const parsed = extractJson(raw);

    if (parsed.body) {
      const body =
        cleanGeneratedBody(parsed.body);

      /**
       * If body is empty after cleaning,
       * use fallback template.
       */
      if (!body) {
        return templateEmail(
          app,
          settings
        );
      }

      /**
       * Subject is ALWAYS generated here.
       *
       * AI has no control over the subject.
       */
      const subject =
        createSubject(app);

      /**
       * Append the verified contact block.
       */
      const finalBody = [
        body,
        "",
        signatureBlock(settings),
      ].join("\n");

      return {
        subject,
        body: finalBody,
        source: "ai",
      };
    }
  } catch {
    /**
     * Any API, network, parsing,
     * or provider error falls back
     * to the template.
     */
  }

  return templateEmail(
    app,
    settings
  );
}